sudo: required
addons:
    chrome: stable
language: node_js
node_js:
    - node
script:
    - npm run test:lib:ci
    - npm run build:lib:ci
before_deploy:
    - cd dist/ngx-plug-n-play-lib
deploy:
    provider: npm
    email: preston.j.lamb@gmail.com
    api_key:
        secure: $NPM_KEY
    on:
        tags: true
        repo: pjlamb12/ngx-plug-n-play
        branch: travis-ci
